### ISSUE TITLE
Error with a GUID route parameter

### ISSUE THREAD

**Issue by SBFrancies** [Kahbazi/MediatR.AspNetCore.Endpoints#10]
I'm seeing an error when using a `System.Guid` type route parameter:

Sample code:

```
namespace Test2
{
    public class SampleRequest2 : IRequest<SampleResponse2>
    {
        public Guid Id { get; set; }
    }

    public class SampleResponse2
    {
        public Guid Id { get; set; }

        public DateTime Timestamp { get; set; }
    }

    [ApiController]
    public class SampleRequestHandler : IRequestHandler<SampleRequest2, SampleResponse2>
    {
        [HttpGet("Test/{id}")]
        public async Task<SampleResponse2> Handle([FromRoute] SampleRequest2 request, CancellationToken cancellationToken)
        {
            return new SampleResponse2
            {
                Id = request.Id,
                Timestamp = DateTime.Now
            };
        }
    }
}
```

Error message:

> System.InvalidCastException: Invalid cast from 'System.String' to 'System.Guid'.
>    at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
>    at System.String.System.IConvertible.ToType(Type type, IFormatProvider provider)
>    at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
>    at System.Convert.ChangeType(Object value, Type conversionType)
>    at MediatR.AspNetCore.Endpoints.EndpointRouteBuilderExtensions.MapRouteData(IMediatorEndpointMetadata requestMetadata, RouteData routeData, Object model)
>    at MediatR.AspNetCore.Endpoints.EndpointRouteBuilderExtensions.MediatorRequestDelegate(HttpContext context)
>    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
>    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
>    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
>    at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
>    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by Kahbazi** [comment]
@SBFrancies thanks for reporting this issue. Guid binding from route is now available in [version 3.1.0 ](https://www.nuget.org/packages/MediatR.AspNetCore.Endpoints/3.1.0).
