### ISSUE TITLE
IAuthorizationService  / Authorize support

### ISSUE THREAD

**Issue by mdissel** [Kahbazi/MediatR.AspNetCore.Endpoints#3]
Any tips how to extend this library with the standard Authorize attribute in combination with IAuthorizationService?

**Comment by Kahbazi** [comment]
You should be able to inject `IAuthorizationService` to request handlers the same way you inject them in Controllers.
What are you trying to achieve? Do you have anything special in mind?

**Comment by mdissel** [comment]
This is what i have in mind, define the attribute on the IRequest class..

```
[Authorize("Policy")]
public class SampleRequest : IRequest<SampleResponse>
    {
        public int Id { get; set; }
    }

```

**Comment by mdissel** [comment]
I'm not sure, but maybe something like this in the EndpointRouteBuilderExtensions.MapMediatR()

```
var builder = endpointsBuilder.Map(routePattern, MediatorRequestDelegate);
var authorizeAttributes = endpoint.RequestType.GetCustomAttributes(inherit:true).OfType<Microsoft.AspNetCore.Authorization.IAuthorizeData>().ToArray();
if (authorizeAttributes.Length > 0 && !authorizeAttributes.OfType<Microsoft.AspNetCore.Authorization.IAllowAnonymous>().Any()) {
     builder.RequireAuthorization(authorizeAttributes.ToArray());
builder.WithDisplayName(endpoint.RequestType.Name);
```

**Comment by mdissel** [comment]
It works out of the box if you add the attribute on the "Handle" method like this:
```
[HttpPost("SampleRequest")]
[Authorize("Policy")]
public async Task<SampleResponse> Handle(SampleRequest request, CancellationToken cancellationToken){
}

```

**Comment by Kahbazi** [comment]
You are correct. Any attribute on `Handle` method will be added as the `Endpoint.Metadata`. So you can add attributes like `[Authorize]` and `[Cors]` and it will work just like the MVC.
