### ISSUE TITLE
Prevent all handlers to be registered as Endpont

### ISSUE THREAD

**Issue by mdissel** [Kahbazi/MediatR.AspNetCore.Endpoints#4]
Currently all handlers are registered as Endpoint. Maybe make this line an optin/out option to only register handlers that have a HttpMethodAttribute.

https://github.com/Kahbazi/MediatR.AspNetCore.Endpoints/blob/daa8263c86d53493b84556c493bc94fe57596635/src/MediatR.AspNetCore.Endpoints/ServiceCollectionExtensions.cs#L48

**Comment by Kahbazi** [comment]
That's a good idea, I will add this feature for the next version.

**Comment by Kahbazi** [comment]
This feature has been implemented in [2.0.0-preview.1](https://www.nuget.org/packages/MediatR.AspNetCore.Endpoints/2.0.0-preview.1).
