### ISSUE TITLE
Json serialization configuration

### ISSUE THREAD

**Issue by vnikolov88** [Kahbazi/MediatR.AspNetCore.Endpoints#5]
Currently, there is no way to configure the Syste.Text.Json serializer, this leads to camel case data sent from most SPA apps not be deserialized properly, we need some way to configure this or have at least

``new JsonSerializerOptions { PropertyNameCaseInsensitive = true, PropertyNamingPolicy = JsonNamingPolicy.CamelCase }``

in the EndpointRouteBuilderExtensions.cs

**Comment by Kahbazi** [comment]
Thanks for your suggestion. This feature has been implemented in [2.0.0-preview.1](https://www.nuget.org/packages/MediatR.AspNetCore.Endpoints/2.0.0-preview.1).

**Comment by vnikolov88** [comment]
Really appreciate you pushing out preview1, I tested it out and this part is OK but the same camalcase formatting needs to be applied to the response serialization as well, the son formatted settings can be exposed from a static property or something to give out more flexibility.

**Comment by Kahbazi** [comment]
Now `JsonSerializerOptions` is applied to both request and response.
https://github.com/Kahbazi/MediatR.AspNetCore.Endpoints/blob/4e6ef834f197a4400be2848d17698b3319517e98/src/MediatR.AspNetCore.Endpoints/EndpointRouteBuilderExtensions.cs#L54
https://github.com/Kahbazi/MediatR.AspNetCore.Endpoints/blob/4e6ef834f197a4400be2848d17698b3319517e98/src/MediatR.AspNetCore.Endpoints/EndpointRouteBuilderExtensions.cs#L84

You should be able to config it in `AddMediatREndpoints` method.

```csharp
services.AddMediatREndpoints(options =>
{
    options.JsonSerializerOptions = new JsonSerializerOptions
    {
        PropertyNameCaseInsensitive = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase
    };
});
```
